---
language: ruby
rvm:
  - 2.8.0-dev
  - 2.7.1
  - 2.6.6
  - 2.5.8
  - 2.4.10
  - jruby-9.2.11.1
  - ruby-head
  - truffleruby
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.8.0-dev
  fast_finish: true
gemfile:
  - Gemfile
before_script:
  - bundle exec rake travis:before -t
script: bundle exec rake travis
after_script:
  - bundle exec rake travis:after -t
sudo: false
